

WITH GRAND_PARENT AS (
SELECT ID, PARENT_ID
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL),
PARENT AS (
SELECT e.ID, e.PARENT_ID
FROM ECOLI_DATA e, GRAND_PARENT g
WHERE e.PARENT_ID = g.ID
)


SELECT e.ID
FROM ECOLI_DATA e, PARENT p
WHERE e.PARENT_ID = p.ID
ORDER BY ID ASC;