SELECT e.ID, IFNULL(CHILD_COUNT, 0) as CHILD_COUNT
FROM 
ECOLI_DATA e LEFT JOIN
(
    SELECT p.ID, COUNT(*) as CHILD_COUNT
    FROM ECOLI_DATA p INNER JOIN ECOLI_DATA c
    ON c.PARENT_ID = p.ID
    GROUP BY p.ID
) as cc
ON e.ID = cc.ID
ORDER BY e.ID