SELECT 
s.SALES_DATE,
s.PRODUCT_ID,
SUM(s.SALES_AMOUNT)
FROM (
SELECT
    SALES_DATE,
    PRODUCT_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE
UNION ALL
SELECT
    SALES_DATE,
    PRODUCT_ID,
    SALES_AMOUNT
FROM
    OFFLINE_SALE
    ) AS s
WHERE '2022-03-01' <= s.SALES_DATE AND s.SALES_DATE <= '2022-03-31'
GROUP BY s.SALES_DATE, s.PRODUCT_ID