-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, COUNT(DISTINCT info.USER_ID) AS USERS
FROM USER_INFO info JOIN ONLINE_SALE sale ON info.USER_ID = sale.USER_ID
WHERE info.GENDER is NOT NULL
group by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
YEAR ASC,
MONTH ASC,
GENDER ASC;

# SELECT *
# FROM USER_INFO info JOIN ONLINE_SALE sale ON info.USER_ID = sale.USER_ID
# WHERE info.GENDER is NOT NULL