SELECT
    CAR_ID,
    CASE
        WHEN MAX(USED) = 1 THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT
        CAR_ID,
        CASE
            WHEN START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE THEN 1
            ELSE 0
        END AS USED
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS SubQuery
GROUP BY
    CAR_ID
ORDER BY
    CAR_ID DESC;