SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT tree.ITEM_ID
    FROM ITEM_INFO info, ITEM_TREE tree
    WHERE tree.PARENT_ITEM_ID = info.ITEM_ID
    AND info.RARITY = "RARE"
)
ORDER BY ITEM_ID DESC;