SELECT info.ID as ID, name.FISH_NAME as FISH_NAME , info.LENGTH as LENGTH
FROM FISH_INFO info JOIN FISH_NAME_INFO name ON info.FISH_TYPE = name.FISH_TYPE
WHERE (info.FISH_TYPE, info.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
FROM FISH_INFO
GROUP BY FISH_TYPE

)